version: '3'
 
services:

    php:
        build:
            context: ./docker/php
        expose:
            - 9000
        volumes:
            - ./app:/srv/www/api
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./docker/php/msmtprc:/etc/msmtprc
            - ./docker/php/php.conf:/usr/local/etc/php/conf.d/custom.ini:ro
            - ./logs/php:/var/log
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            HOTCRP_PAPER_SITE: ${HOTCRP_PAPER_SITE}
            HOTCRP_CONTACT_NAME: ${HOTCRP_CONTACT_NAME}
            HOTCRP_EMAIL_CONTACT: ${HOTCRP_EMAIL_CONTACT}
            HOTCRP_EMAIL_FROM:  ${HOTCRP_EMAIL_FROM}
            
    nginx:
        image: nginx:alpine
        ports:
            - 9001:80
        volumes:
            - ./app:/srv/www/api
            - ./logs/nginx:/var/log/nginx  
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
 
    mysql:
        image: mysql:5.7
        command: --max_allowed_packet=10485760
        volumes:
            - ./app:/srv/www/api
            - ./dbdata:/var/lib/mysql
        expose:
            - 3306
        depends_on:
            - php
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

