version: '3'
 
services:
    
    # If you want to test the mail server and see
    # in a web interface what are the sent mail, uncomment this
    # and comment the other smtp container.
    # The web interface is accessible at localhost:9002
    # smtp:
    #     image: mailhog/mailhog:v1.0.1
    #     restart: always
    #     expose:
    #         - "25"
    #     environment:
    #         MH_SMTP_BIND_ADDR: 0.0.0.0:25
    #     ports:
    #         - 9002:8025

    smtp:
      image: bytemark/smtp
      expose:
        - "25"
      environment:
        MAILNAME: ${SERVER_HOSTNAME}
    
    # smtp:
    #     build:
    #         context: ./docker/smtp
    #     restart: always
    #     expose:
    #         - "25"
    #     volumes:
    #         - ./mail-spool:/var/spool/postfix
    #         # you can store mail log in a volume 
    #         # (but create the file locally before startup)
    #         #- ./logs/smtp/maillog:/var/log/maillog
    #     environment:
    #         SMTP_SERVER: ${SMTP_SERVER}
    #         SMTP_PORT: ${SMTP_PORT}
    #         SMTP_USERNAME: ${SMTP_USERNAME}
    #         SMTP_PASSWORD:  ${SMTP_PASSWORD}
    #         SERVER_HOSTNAME: ${SERVER_HOSTNAME}
    #         DESTINATION_CONCURRENCY_LIMIT: "1"
    #         DESTINATION_RATE_DELAY: "1s"


    php:
        build:
            context: ./docker/php
        expose:
            - 9000
        restart: always
        volumes:
            - ./app:/srv/www/api
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./docker/php/msmtprc:/etc/msmtprc
            - ./docker/php/php.conf:/usr/local/etc/php/conf.d/custom.ini:ro
            - ./logs/php:/var/log
        environment:
            MYSQL_USER: hotcrp
            MYSQL_PASSWORD: hotcrppwd
            MYSQL_DATABASE: hotcrp
            MYSQL_ROOT_PASSWORD: root
            HOTCRP_PAPER_SITE: ${HOTCRP_PAPER_SITE}
            HOTCRP_CONTACT_NAME: ${HOTCRP_CONTACT_NAME}
            HOTCRP_EMAIL_CONTACT: ${HOTCRP_EMAIL_CONTACT}
            HOTCRP_EMAIL_FROM:  ${HOTCRP_EMAIL_FROM}
        depends_on:
            - smtp
    nginx:
        image: nginx:alpine
        restart: always
        ports:
            - 9001:80
        volumes:
            - ./app:/srv/www/api
            - ./logs/nginx:/var/log/nginx  
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
 
    mysql:
        image: mysql:8.0.26
        restart: always
        command: --max_allowed_packet=20485760
        volumes:
            - ./app:/srv/www/api
            - ./dbdata:/var/lib/mysql
        expose:
            - 3306
        depends_on:
            - php
        environment:
            MYSQL_USER: hotcrp
            MYSQL_PASSWORD: hotcrppwd
            MYSQL_DATABASE: hotcrp
            MYSQL_ROOT_PASSWORD: root

